import Project1 from "/assets/project/project1.jpg";
import Project2 from "/assets/project/project2.webp";
import Project3 from "/assets/project/project3.jpg";
import Project4 from "/assets/project/project4.jpg";
import Project5 from "/assets/project/project5.jpg";
import Project6 from "/assets/project/project6.jpg";

export const listProject = [
  {
    id: 1,
    image: Project1,
    title: "NovaTrend E-Commerce Platform",
    tech: "React • Node.js • Express • PostgreSQL • Prisma • Docker",
    subtitle: "A full-stack e-commerce platform built with a production-style architecture, featuring authentication, product management, shopping cart, and order workflows.",
    fullDescription: "A full-stack e-commerce platform built with a production-style architecture, featuring authentication, product management, shopping cart, and order workflows.",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/cungcung-design/ecommerce-project",
    liveUrl: "https://ecommerce-frontend-yn2u.onrender.com/",
    dad: "100",
  },
  {
    id: 2,
    image: Project2,
    title: "Chin Fashion — Traditional Fashion E-Commerce",
    tech: "React • Node.js • Express • MongoDB • Tailwind",
    subtitle: "A traditional fashion e-commerce platform focused on clean product presentation, category browsing, and a boutique shopping experience.",
    fullDescription: "A traditional fashion e-commerce platform focused on clean product presentation, category browsing, and a boutique shopping experience.",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/cungcung-design/Chin_Shop",
    liveUrl: "https://chin-fashion.vercel.app/",
    dad: "200",
  },
  {
    id: 3,
    image: Project3,
    title: "Hotel Management & Booking System",
    tech: "Laravel • PHP • MySQL • Blade • CSS",
    subtitle: "A web-based hotel booking system for managing rooms and reservations. It allows users to view available rooms and make bookings easily.",
    fullDescription: "A web-based hotel booking system for managing rooms and reservations. It allows users to view available rooms and make bookings easily.",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/cungcung-design/self-learning/tree/main/laravel_project/hotel_project",
    hideLiveDemo: true,
    dad: "300",
  },
  {
    id: 4,
    image: Project4,
    title: "Smart POS — Desktop Point-of-Sale System",
    tech: "Python • Tkinter • MySQL",
    subtitle: "A desktop POS system for managing products, inventory, and sales. It also includes stock movements and receipt management for a simple business workflow.",
    fullDescription: "A desktop POS system for managing products, inventory, and sales. It also includes stock movements and receipt management for a simple business workflow.",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/cungcung-design/python/tree/main/posFile",
    hideLiveDemo: true,
    dad: "400",
  },
  {
    id: 5,
    image: Project5,
    title: "SaaS Dashboard — Analytics & Management Platform",
    tech: "Next.js • TypeScript • Prisma • PostgreSQL • Tailwind",
    subtitle: "A SaaS management dashboard focused on data and user management. It provides analytics, access control, filtering, bulk actions, and activity logs.",
    fullDescription: "A SaaS management dashboard focused on data and user management. It provides analytics, access control, filtering, bulk actions, and activity logs.",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/cungcung-design/nova",
    hideLiveDemo: true,
    dad: "500",
  },
  {
    id: 6,
    image: Project6,
    title: "Music App — Mobile Music Application",
    tech: "Flutter • Dart",
    subtitle: "A mobile music application built with Flutter for browsing and exploring music. It features clean navigation, responsive layouts, and a simple user-friendly interface.",
    fullDescription: "A mobile music application built with Flutter for browsing and exploring music. It features clean navigation, responsive layouts, and a simple user-friendly interface.",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/cungcung-design/music-app-project",
    hideLiveDemo: true,
    dad: "600",
  },
];
